FROM python:3.10-slim
WORKDIR /app
COPY requirements_frontend.txt .
RUN pip install -r requirements_frontend.txt
# Копируем папку frontend целиком внутрь /app
COPY ./frontend /app/frontend
EXPOSE 8000
# Запускаем, указывая полный путь "пакет.модуль:объект"
CMD ["uvicorn", "frontend.main:app", "--host", "0.0.0.0", "--port", "8000"]
