# Это конфигурация для доступа к Kubernetes-кластеру в VK Cloud. Она содержит секретные данные.
# Её нужно скачивать каждый раз заново при создании кластера (то есть после 'terraform apply')
# (я скачивал из UI на сайте VK Cloud в своём проекте).

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LE0...S0tGg==  # тут какие-то данные
    server: https://212.233.90.51:6443  # тут указывается внешний адрес нашего кластера
  name: reminder-app-cluster
contexts:
- context:
    cluster: reminder-app-cluster
    user: reminder-app-cluster
  name: default/reminder-app-cluster
current-context: default/reminder-app-cluster
kind: Config
preferences: {}
users:
- name: reminder-app-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: client-keystone-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://infra.mail.ru:35357/v3/"
      - name: "OS_USERNAME"
        value: "myemail@example.ru"  # тут логин будет
      #- name: "OS_PASSWORD"
      #  value: "put your password here"
      - name: "OS_PROJECT_ID"
        value: "113...ae"            # тут id проекта
      - name: "OS_DOMAIN_NAME"
        value: "users"
      interactiveMode: IfAvailable
      provideClusterInfo: false