{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "trickster.fullname" . }}
{{- $servicePort := .Values.service.servicePort -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: trickster-ingress
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "trickster.labels" . | nindent 4 }}
{{- range $key, $value := .Values.ingress.extraLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}  
{{- end }}
