{{- range .Values.volumes }}
{{- if and (eq .type "persistentVolume") .enabled}}
{{- if (eq .existingClaim "") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "trickster.labels" $ | nindent 4 }}
  name: {{ .volName | printf "trickster-%s-claim" }}
spec:
  accessModes:
{{ toYaml .accessModes | indent 4 }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .size }}"
{{- end -}}
{{- end -}}
{{- end -}}
